M2 feature
krishnzzz/react-calculator pull request #5
Opened 2021-03-09 17:03 UTC by krishnzzz

In this feature the following have been done.

- Create App, ButtonPanel and Button components
- Add buttons and symbol

Thank you.

2021-03-09 17:43 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

##### `Display` component

* [x] it is placed in `src/components` directory ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/addToComponent.png))
* [ ] it accepts `the result of the calculation` as an incoming prop ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/incomingProps.png))
* [x] its result prop should be a String with default value = 0 ([should be String screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)) ([default props screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png))

- [x] more below 👇 

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-03-09 17:43 UTC, Spayco commented on src/App.js
> +  </div>
* [ ] it should be placed in `src/components` directory ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/App.png))
* [ ] it should render the `Display` component ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/appFunctionalComponent.png))
* [ ] it should have children components wrapped in [React.Fragment](https://reactjs.org/docs/fragments.html#short-syntax) short syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/ReactFragment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896092/))

2021-03-09 17:43 UTC, Spayco commented on src/ButtonPanel.js
> +);
- [ ] it includes all the following buttons divided in the groups below: ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/buttonPanel/buttons.png))

* Group 1: AC, +/-, %, ÷
* Group 2: 7, 8, 9, X
* Group 3: 4, 5, 6, -
* Group 4: 1, 2, 3, +
* Group 5: 0, ., =


the `Button` component should be used **once** per each symbol

2021-03-09 17:43 UTC, Spayco commented on src/Button.js
> +};
- [ ] don't map the symbols, instead, you should get **one** symbol as a prop that gets rendered as a `<button>` tag

2021-03-10 15:25 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi :hand: @krishnzzz 
Awesome job on this milestone so far. but we still need to make some changes before moving on.

- [x] Check my comments below.

**OPTIONAL**
- [ ] Awesome job add descriptive information about the project to your README file. This is really good because increases the professionalism of your repository. However, the text generated by create-react-app it's still there and we can safely remove it. 

Happy coding :computer: 
**Sérgio Torres**

2021-03-10 15:25 UTC, Torres-ssf commented on src/components/App.js
> +  </div>
- [ ] App component should have its children components wrapped in React.Fragment short syntax:
```JS
const App = () => (
  <>
    <Display result="0" />
    <ButtonPanel />
  </>
```
![Screenshot from 2021-03-10 12-11-58](https://user-images.githubusercontent.com/30977845/110651118-e95b8280-8199-11eb-9eab-3580ac2fdca0.png)

- [ ] There is no need to pass the `result` prop to the Display component yet. That's why we can declare a default value for it inside the component.

2021-03-10 15:25 UTC, Torres-ssf commented on src/components/Display.js
> +};
- [x] The `result` prop should be a String with default value = '0'
```JS
Display.defaultProps = {
  result: '0',
};

Button.propTypes = {
  result: PropTypes.string,
};
```
![Screenshot from 2021-03-10 12-17-08](https://user-images.githubusercontent.com/30977845/110651902-a1892b00-819a-11eb-8be5-fd96e94fe940.png)
![Screenshot from 2021-03-10 12-17-38](https://user-images.githubusercontent.com/30977845/110651920-a5b54880-819a-11eb-99d6-0c71e4162353.png)

2021-03-11 12:09 UTC, Torres-ssf approved these changes
### Milestone Approved :+1: 
Hi again @krishnzzz :hand: 
Great job implementing the requested changes.
You may merge the PR.
Good luck with the next milestone.

Happy coding :computer: 
**Sérgio Torres**

2021-03-11 13:53 UTC, merged